package com.traviswyatt.ioio.Adxl345Hmc5883lANN;


import java.io.IOException;
import java.io.OutputStream;

import android.content.Context;

public class XbeeControl {
    // The Xbee API Frame is generated by http://ftp1.digi.com/support/utilities/digi_apiframes2.htm
    // The Remote AT Command is used to control the D1 of Xbee Pro
	
	//Set remote D1 output High:
	//7E 00 10 17 00 00 13 A2 00 40 A2 69 F7 FF FE 02 44 31 05 78
	
	//Set remote D1 output Low:
	//7E 00 10 17 00 00 13 A2 00 40 A2 69 F7 FF FE 02 44 31 04 79
	
	//Set remote D2 output High:
	//7E 00 10 17 00 00 13 A2 00 40 A2 69 F7 FF FE 02 44 32 05 77
	
	//Set remote D2 output Low:
	//7E 00 10 17 00 00 13 A2 00 40 A2 69 F7 FF FE 02 44 32 04 78
	
	public static final byte Delimiter          = (byte) 0x7E;
	public static final byte LengthH       		= (byte) 0x00;
	public static final byte LengthL       		= (byte) 0x10;
	public static final byte API    		    = (byte) 0x17;
	public static final byte FrameID        	= (byte) 0x00;
	
	public static final byte DestAddr64H1          = (byte) 0x00;
	public static final byte DestAddr64H2          = (byte) 0x13;
	public static final byte DestAddr64H3          = (byte) 0xA2;
	public static final byte DestAddr64H4          = (byte) 0x00;
	public static final byte DestAddr64L1          = (byte) 0x40;
	public static final byte DestAddr64L2          = (byte) 0xA2;
	public static final byte DestAddr64L3          = (byte) 0x69;
	public static final byte DestAddr64L4          = (byte) 0xF7;
	
	public static final byte DestAddr16H           = (byte) 0xFF;
	public static final byte DestAddr16L           = (byte) 0xFE;
	
	public static final byte CmdOptions            = (byte) 0x02;
	public static final byte ATCmd1				   = (byte) 0x44; //D
	public static final byte ATCmd2_1				   = (byte) 0x31; //1
	public static final byte ATCmd2_2				   = (byte) 0x32; //2
	
	public static final byte OutputHigh			   = (byte) 0x05;
	public static final byte OutputLow			   = (byte) 0x04;
	
	public static final byte CheckSumHighD1			   = (byte) 0x78;
	public static final byte CheckSumLowD1			   = (byte) 0x79;
	public static final byte CheckSumHighD2 		   = (byte) 0x77;
	public static final byte CheckSumLowD2			   = (byte) 0x78;
	OutputStream out;
	
	public XbeeControl(OutputStream Out) {
		this.out = Out;
	}
	
	public void SendHighD1(){
				
		try {
			out.write(Delimiter);
			out.write(LengthH);
			out.write(LengthL);
			out.write(API);
			out.write(FrameID);
			
			out.write(DestAddr64H1);
			out.write(DestAddr64H2);
			out.write(DestAddr64H3);
			out.write(DestAddr64H4);
			out.write(DestAddr64L1);
			out.write(DestAddr64L2);
			out.write(DestAddr64L3);
			out.write(DestAddr64L4);
			
			out.write(DestAddr16H);
			out.write(DestAddr16L);
			
			out.write(CmdOptions);
			out.write(ATCmd1);
			out.write(ATCmd2_1);
			out.write(OutputHigh);
			out.write(CheckSumHighD1);	
			
			System.out.println("Write AT command completed");
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
		
		
	}
	public void SendLowD1(){
		
		try {
			out.write(Delimiter);
			out.write(LengthH);
			out.write(LengthL);
			out.write(API);
			out.write(FrameID);
			
			out.write(DestAddr64H1);
			out.write(DestAddr64H2);
			out.write(DestAddr64H3);
			out.write(DestAddr64H4);
			out.write(DestAddr64L1);
			out.write(DestAddr64L2);
			out.write(DestAddr64L3);
			out.write(DestAddr64L4);
			
			out.write(DestAddr16H);
			out.write(DestAddr16L);
			
			out.write(CmdOptions);
			out.write(ATCmd1);
			out.write(ATCmd2_1);
			out.write(OutputLow);
			out.write(CheckSumLowD1);	
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	
	
}	
	
	public void SendHighD2(){
		
		try {
			out.write(Delimiter);
			out.write(LengthH);
			out.write(LengthL);
			out.write(API);
			out.write(FrameID);
			
			out.write(DestAddr64H1);
			out.write(DestAddr64H2);
			out.write(DestAddr64H3);
			out.write(DestAddr64H4);
			out.write(DestAddr64L1);
			out.write(DestAddr64L2);
			out.write(DestAddr64L3);
			out.write(DestAddr64L4);
			
			out.write(DestAddr16H);
			out.write(DestAddr16L);
			
			out.write(CmdOptions);
			out.write(ATCmd1);
			out.write(ATCmd2_2);
			out.write(OutputHigh);
			out.write(CheckSumHighD2);	
			
			System.out.println("Write AT command completed");
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
		
		
	}
	public void SendLowD2(){
		
		try {
			out.write(Delimiter);
			out.write(LengthH);
			out.write(LengthL);
			out.write(API);
			out.write(FrameID);
			
			out.write(DestAddr64H1);
			out.write(DestAddr64H2);
			out.write(DestAddr64H3);
			out.write(DestAddr64H4);
			out.write(DestAddr64L1);
			out.write(DestAddr64L2);
			out.write(DestAddr64L3);
			out.write(DestAddr64L4);
			
			out.write(DestAddr16H);
			out.write(DestAddr16L);
			
			out.write(CmdOptions);
			out.write(ATCmd1);
			out.write(ATCmd2_2);
			out.write(OutputLow);
			out.write(CheckSumLowD2);	
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
	
	
}
	
}
